project:
  type: book

execute: 
  freeze: true

book:
  title: "√Ålgebra"
  subtitle: Apostilas para disciplinas, UFMG, 2024
  author: "Csaba Schneider"
  date: "Criado e atualizado 2024/I"
  chapters:
    - index.qmd
    - part: IniciacaoAMatematica/index.qmd
      chapters: 
        - IniciacaoAMatematica/prop.qmd
        - IniciacaoAMatematica/conjuntos.qmd
        - IniciacaoAMatematica/quant.qmd
        - IniciacaoAMatematica/relations.qmd
        - IniciacaoAMatematica/equivalence.qmd
        - IniciacaoAMatematica/equivalence_examples.qmd
        - IniciacaoAMatematica/order.qmd
        - IniciacaoAMatematica/functions.qmd
        - IniciacaoAMatematica/naturais.qmd
        - IniciacaoAMatematica/int_rat.qmd
    - part: FundamentosDeAlgebra/index.qmd
      chapters: 
        - FundamentosDeAlgebra/divisao.qmd
        - FundamentosDeAlgebra/expansao.qmd
        - FundamentosDeAlgebra/racionais.qmd
        - FundamentosDeAlgebra/mdc.qmd
        - FundamentosDeAlgebra/primos.qmd
        - FundamentosDeAlgebra/diof.qmd
        - FundamentosDeAlgebra/phi.qmd
        - FundamentosDeAlgebra/cong.qmd
        - FundamentosDeAlgebra/res_classes.qmd
        - FundamentosDeAlgebra/cong_incog.qmd
        - FundamentosDeAlgebra/fermat_euler.qmd
        - FundamentosDeAlgebra/ordr.qmd
        - FundamentosDeAlgebra/quadrados.qmd
        - FundamentosDeAlgebra/exp.qmd
        - FundamentosDeAlgebra/miller.qmd
        - FundamentosDeAlgebra/rsa_p1.qmd
        - FundamentosDeAlgebra/aneis.qmd
        - FundamentosDeAlgebra/complex.qmd
        - FundamentosDeAlgebra/pols.qmd
        - FundamentosDeAlgebra/div_pol.qmd
        - FundamentosDeAlgebra/mdc_pol.qmd
        - FundamentosDeAlgebra/roots.qmd
        - FundamentosDeAlgebra/primitive_p2.qmd
        - FundamentosDeAlgebra/irred.qmd
        - FundamentosDeAlgebra/dfu.qmd
        - FundamentosDeAlgebra/gauss_pt1.qmd
        - FundamentosDeAlgebra/quadratic.qmd

    - part: AlgebraLinearII/index.qmd
      chapters: 
        - AlgebraLinearII/bases.qmd
        - AlgebraLinearII/subespacos.qmd
        - AlgebraLinearII/quociente.qmd
        - AlgebraLinearII/trans_lin.qmd
        - AlgebraLinearII/matrizes.qmd
        - AlgebraLinearII/dual.qmd
        - AlgebraLinearII/formas.qmd
        - AlgebraLinearII/autovals.qmd
        - AlgebraLinearII/pol_min.qmd
        - AlgebraLinearII/cayley_hamilton.qmd
        - AlgebraLinearII/projecoes.qmd
        - AlgebraLinearII/primaria.qmd
        - AlgebraLinearII/nilpotentes.qmd
        - AlgebraLinearII/unicidade_jordan.qmd
        - AlgebraLinearII/cyclic.qmd
        - AlgebraLinearII/sesqui.qmd
        - AlgebraLinearII/isometrias.qmd
        - AlgebraLinearII/adjuntos.qmd
        - AlgebraLinearII/autoadjuntos.qmd
        - AlgebraLinearII/normais.qmd
        - AlgebraLinearII/ortogonais.qmd
        - AlgebraLinearII/so_2_so_3.qmd
    - part:  GruposECorpos/index.qmd
      chapters:
        - GruposECorpos/definitions.qmd
        - GruposECorpos/lagrange.qmd
        - GruposECorpos/geradores.qmd
        - GruposECorpos/normais.qmd
        - GruposECorpos/products.qmd
        - GruposECorpos/actions.qmd
        - GruposECorpos/classes.qmd
        - GruposECorpos/alternado.qmd
        - GruposECorpos/sylow.qmd
        - GruposECorpos/abelian.qmd
        - GruposECorpos/soluble.qmd
        - GruposECorpos/livres.qmd
        - GruposECorpos/psl.qmd
        - GruposECorpos/nilpotent.qmd 
        - GruposECorpos/ringsfields.qmd
        - GruposECorpos/extensions.qmd
        - GruposECorpos/decompfields.qmd
        - GruposECorpos/fieldauts.qmd
        - GruposECorpos/galois.qmd
        - GruposECorpos/appl_galois.qmd
format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    fontsize: 12pt
    include-in-header:
      - file: macros.html
    grid:
      sidebar-width: 200px
      body-width: 800px
      margin-width: 600px
      gutter-width: 1.5rem
#  pdf:
#    include-in-header:
#      - file: "macros.tex"